// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/hezbymuhammad/payment-gateway/domain"
	mock "github.com/stretchr/testify/mock"
)

// MerchantUsecase is an autogenerated mock type for the MerchantUsecase type
type MerchantUsecase struct {
	mock.Mock
}

// SetChild provides a mock function with given fields: ctx, mg
func (_m *MerchantUsecase) SetChild(ctx context.Context, mg *domain.MerchantGroup) error {
	ret := _m.Called(ctx, mg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MerchantGroup) error); ok {
		r0 = rf(ctx, mg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields: ctx, m
func (_m *MerchantUsecase) Store(ctx context.Context, m *domain.Merchant) error {
	ret := _m.Called(ctx, m)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Merchant) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
