// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/hezbymuhammad/payment-gateway/domain"
	mock "github.com/stretchr/testify/mock"
)

// TransactionUsecase is an autogenerated mock type for the TransactionUsecase type
type TransactionUsecase struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TransactionUsecase) GetByID(ctx context.Context, id int64) (domain.Transaction, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, t
func (_m *TransactionUsecase) Store(ctx context.Context, t *domain.Transaction) error {
	ret := _m.Called(ctx, t)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, t
func (_m *TransactionUsecase) Update(ctx context.Context, t *domain.Transaction) error {
	ret := _m.Called(ctx, t)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
