version: '3'

services:
  app:
    command: ["sh", "-c", "make build && ./bin/main"]
    image: golang:1.16
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - home:/root
      - gocache:/go
      - .:/app

volumes:
  home:
  gocache:
